My Database name is – “Akki” as per source of dataset and table name is – “Car_Dekho”.
Create Database Akki;



----Then upload it in MySql----

>>>>PROBLEMS WITH SOLUTIONS<<<<

---1.	How many Cars are available yearwise?
SELECT year as YEARS, COUNT(NAME) AS TOTAL 
FROM CAR_DEKHO GROUP BY YEAR;
---2.	A complete count list of all cars between 2015 and 2023.
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR BETWEEN 2015 AND 2023;

----3.	How many cars are available in 2020, 2021, 2022?
SELECT YEAR, COUNT(NAME) AS TOTAL
FROM CAR_DEKHO 
WHERE YEAR = 2020 OR YEAR = 2021 OR YEAR = 2022
GROUP BY year;

----4.	How many diesel cars available in 2020?
SELECT YEAR, COUNT(FUEL) AS DIESEL_CARDS FROM CAR_DEKHO
WHERE FUEL = 'DIESEL' AND YEAR = 2020 GROUP BY year;

----5.	In which Years having more than 100 cars?
SELECT YEAR, COUNT(*) AS TOTAL FROM CAR_DEKHO
GROUP BY YEAR HAVING TOTAL > 100;

----6.	Total No.s of all category cars yearwise.
SELECT year as YEARS, 
SUM(CASE WHEN FUEL = 'PETROL' THEN 1 ELSE 0 END) AS PETROL,
SUM(CASE WHEN FUEL = 'DIESEL' THEN 1 ELSE 0 END) AS DIESEL,
SUM(CASE WHEN FUEL = 'ELECTRIC' THEN 1 ELSE 0 END) AS ELECTRIC,
SUM(CASE WHEN FUEL = 'CNG' THEN 1 ELSE 0 END) AS CNG,
SUM(CASE WHEN FUEL = ‘LPG’ THEN 1 ELSE 0 END) AS LPG
FROM CAR_DEKHO GROUP BY YEAR;

----7.	Yearwise and fuel categorywise report with Yearwise total.
SELECT 
    YEAR AS YEARS, 
    SUM(CASE WHEN FUEL = 'PETROL' THEN 1 ELSE 0 END) AS PETROL,
    SUM(CASE WHEN FUEL = 'DIESEL' THEN 1 ELSE 0 END) AS DIESEL,
    SUM(CASE WHEN FUEL = 'ELECTRIC' THEN 1 ELSE 0 END) AS ELECTRIC,
    SUM(CASE WHEN FUEL = 'CNG' THEN 1 ELSE 0 END) AS CNG,
    SUM(CASE WHEN FUEL = 'LPG' THEN 1 ELSE 0 END) AS LPG,
    SUM(CASE WHEN FUEL IN ('PETROL','DIESEL','ELECTRIC','CNG','LPG')
		THEN 1 ELSE 0 END) AS TOTAL_YEARWISE
        FROM CAR_DEKHO GROUP BY YEAR;

----8.	Total Yearwise selling price.
SELECT YEAR AS YEARS, sum(selling_price) as TOTAL
FROM CAR_DEKHO GROUP BY YEAR;

----9.	Total Selling_Price yearwise and fuel category wise.
SELECT YEAR AS YEARS, 
	SUM(CASE WHEN FUEL = 'DIESEL' THEN SELLING_PRICE ELSE 0 END) AS DIESEL,
    SUM(CASE WHEN FUEL = 'PETROL' THEN SELLING_PRICE ELSE 0 END) AS PETROL,
    SUM(CASE WHEN FUEL = 'ELECTRIC' THEN SELLING_PRICE ELSE 0 END) AS ELECTRIC,
    SUM(CASE WHEN FUEL = 'LPG' THEN SELLING_PRICE ELSE 0 END) AS LPG,
    SUM(CASE WHEN FUEL = 'CNG' THEN SELLING_PRICE ELSE 0 END) AS CNG,
    SUM(CASE WHEN FUEL IN ('DIESEL','PETROL','ELECTRIC','LPG','CNG') THEN SELLING_PRICE ELSE 0 END)
    AS TOTAL FROM CAR_DEKHO GROUP BY YEAR;
